spring:
  application:
    name: newbie-apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 8769
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
